layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 5
  exclude:
    forks: false
    projects:
    - tsconfig
    - storagecoach

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  twitter: maksimsinik
  linkedin: maksimsinik
  # keybase: fox1t
  # website: https://maksim.dev
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Node.js
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png

  - name: Fastify
    web_url: https://github.com/topics/fastify
    image_url: https://raw.githubusercontent.com/github/explore/d236cc6153f7ab3e68694234be43003b74cfe151/topics/fastify/fastify.png

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/javascript/javascript.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png

  # - name: C
  #   web_url: https://github.com/topics/c
  #   image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/c/c.png
  # - name: Azure
  #   web_url: https://github.com/topics/azure
  #   image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/azure/azure.png
  # - name: Python
  #   web_url: https://github.com/topics/python
  #   image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

orgs:
  - login: "Fastify"
    description: "Fast and low overhead web framework, for Node.js"
    html_url: "https://fastify.io"
    avatar_url: "https://avatars.githubusercontent.com/u/24939410?s=200&v=4"
  - login: "Ducktors"
    description: "We are a collective of OSS contributors."
    html_url: "https://ducktors.dev"
    avatar_url: "https://avatars.githubusercontent.com/u/113586635?s=96&v=4"
  - login: "HospitalRun"
    description: "Open source, modern software for charitable hospitals in the developing world."
    html_url: "https://hospitalrun.io"
    avatar_url: "https://avatars1.githubusercontent.com/u/6797041?v=4"

repositories:
  - html_url: https://github.com/HospitalRun/hospitalrun-frontend
    name: hospitalrun-frontend
    description: Frontend for HospitalRun
    language: TypeScript
    stargazers_count: 6700
    forks_count: 2200
  - html_url: https://github.com/HospitalRun/hospitalrun-server
    name: hospitalrun-server
    description: Backend for HospitalRun
    language: TypeScript
    stargazers_count: 853
    forks_count: 598
  - html_url: https://github.com/HospitalRun/hospitalrun
    name: hospitalrun
    description: Monorepo that holds all of HospitalRun's v2 projects
    language: JavaScript
    stargazers_count: 842
    forks_count: 285
  - html_url: https://github.com/ducktors/turborepo-remote-cache
    name: turborepo-remote-cache
    description: Open source implementation of the Turborepo custom remote cache server.
    language: TypeScript
    stargazers_count: 543
    forks_count: 57
